import { EventEmitter } from 'events';
import OpenAI from 'openai';
import { env } from '../utils/env.js';
import { rzunaCharacter } from './rzuna.character.js';
import type { AlphaSignal } from '@rzuna/contracts';

export interface BroadcastMessage {
  platform: 'telegram' | 'twitter' | 'internal_log';
  content: string;
  metadata: {
    mint: string;
    score: number;
    confidence: string;
  };
}

/**
 * 🧠 ElizaBrain: The Social & Persona Layer (Sidecar)
 * Listens to high-signal alphas generated by the Engine and uses the 
 * rzuna character persona to formulate broadcast messages.
 * 
 * Does NOT block main ingestion pipeline.
 */
export class ElizaBrain extends EventEmitter {
  private openai: OpenAI | null = null;

  constructor() {
    super();
    // Use OpenRouter if available (Blueprint V22.1), fallback to OpenAI
    const apiKey = env.OPENROUTER_API_KEY || env.OPENAI_API_KEY;
    if (apiKey) {
      this.openai = new OpenAI({
        apiKey,
        ...(env.OPENROUTER_API_KEY ? { baseURL: env.OPENROUTER_BASE_URL } : {}),
      });
    } else {
      console.warn('⚠️ [ElizaBrain] No AI Key found. Persona generation will be mocked.');
    }
  }

  /**
   * Listens to Engine signal events and processes them in the background.
   */
  async processSignal(signal: AlphaSignal): Promise<void> {
    try {
      if (!signal.aiReasoning) return;

      // Only broadcast ALPHA or high confidence tokens
      if (signal.aiReasoning.verdict === 'REJECT') return;
      
      const broadcast = await this.generatePersonaMessage(signal);
      
      // Emit the broadcast ready for Telegram/Twitter clients
      this.emit('broadcast', broadcast);
      
    } catch (error) {
      console.error('❌ [ElizaBrain] Failed to process signal:', error);
    }
  }

  /**
   * Injects the structured signal into the rzuna character prompt.
   */
  private async generatePersonaMessage(signal: AlphaSignal): Promise<BroadcastMessage> {
    if (!signal.aiReasoning) {
      throw new Error('Signal missing AI reasoning');
    }

    if (!this.openai) {
      return {
        platform: 'internal_log',
        content: `🚨 ALPHA ALERT: $${signal.symbol} scored ${signal.score}/100. (MOCK PERSONA)`,
        metadata: { mint: signal.mint, score: signal.score, confidence: signal.aiReasoning.confidence || 'UNKNOWN' },
      };
    }

    const systemPrompt = `
      Main Character: ${rzunaCharacter.name} (@${rzunaCharacter.username})
      Bio: ${rzunaCharacter.bio.join(' ')}
      Lore: ${rzunaCharacter.lore.join(' ')}
      Style: ${rzunaCharacter.style.post.join(', ')}

      Task: Create a highly engaging "ALPHA ALERT" broadcast for VIP Telegram members.
      Rules:
      1. Adopt the "rzuna" persona: Pure English crypto degen slang (e.g., aped, nuked, send it, rugged), cold, objective, apex predator vibe limit-testing the chain.
      2. START with a 🚨 emoji and a characteristic greeting (e.g., "Whale tracker triggered.", "New blip on the radar.").
      3. Include the symbol, score, confidence, narrative, and catalysts concisely.
      4. If there are risk factors, state them bluntly.
      5. Length: 3-4 short punchy sentences. Focus strictly on alpha. DO NOT OVERUSE HASHTAGS. No fluff.
    `;

    const prompt = `
      New Token Data (Passed L1 & L2 Filters):
      Symbol: ${signal.symbol}
      Mint: ${signal.mint}
      Score: ${signal.score}/100 
      Confidence: ${signal.aiReasoning.confidence || 'UNKNOWN'}
      AI Narrative: ${signal.aiReasoning.narrative}
      Catalysts: ${signal.aiReasoning.catalysts.join(', ') || 'N/A'}
      Risks: ${signal.aiReasoning.riskFactors.join(', ') || 'None'}
      Entry: ${signal.aiReasoning.entryStrategy || 'N/A'}

      Draft the VIP broadcast message now.
    `;

    try {
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4o-mini', // Fast & cheap for text formatting
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: prompt }
        ],
        temperature: 0.7, // Slightly higher for persona creativity
        max_tokens: 250,
      });

      const content = response.choices[0].message.content || '🚨 ALPHA ALERT: Output generation failed.';

      return {
        platform: 'telegram',
        content: content.trim(),
        metadata: {
          mint: signal.mint,
          score: signal.score,
          confidence: signal.aiReasoning.confidence,
        }
      };

    } catch (err: any) {
      throw new Error('Persona generation failed: ' + err.message);
    }
  }
}
